chat/urls.py
from django.urls import path, re_path
from .views import ThreadView
from . import views

app_name = 'chat'

urlpatterns = [
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

hwj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('messages/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from user.models import Profile
import re
from django.contrib import admin


class ThreadManager(models.Manager):

    def by_user(self, user):

        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()

        return qs

    def get_or_new(self, user, other_username):  # get_or_create

        username = user.username

        if username == other_username:
            return None

        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)

        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()

        if qs.count() == 1:

            return qs.first(), False

        elif qs.count() > 1:

            return qs.order_by('timestamp').first(), False

        else:

            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)

            if user != user2:
                obj = self.model(first=user, second=user2)
                obj.save()
                return obj, True

            return None, False


class Thread(models.Model):

    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    def __str__(self):
        return f'Chat between {self.first} & {self.second}'

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True

        return False


CHAT_STATUS_CHOICES = [
    ('n', 'New'),
    ('c', 'Clean'),
    ('i', 'Inappropriate'),
]


class ChatMessage(models.Model):

    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=CHAT_STATUS_CHOICES, default='n')


def check_message(message):

    phone_number_regex = "\(\w{3}\)\w{3}-\w{4}"

    email_regex = "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"

    if re.search(email_regex, message) or re.search(phone_number_regex, message):

        ret_value = 'i'
        return ret_value

    else:

        ret_value = 'c'
        return ret_value


def search_messages():

    query_all_messages = ThreadManager.ChatMessage.objects.all()

    phone_number_regex= "\(\w{3}\)\w{3}-\w{4}"

    email_regex = "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"

    for message in query_all_messages:

        if re.search(email_regex, message) or re.search(phone_number_regex, message):

            return 'i'

        else:

            return 'c'

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
	message = forms.CharField(
		widget=forms.TextInput(   # TextInput changed to TextArea
			attrs={
				"class": "form-control",
				"placeholder": "Type your message..."
				}
			)
		)

chat/views.py
# Views: grab data to show the user 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.conf import settings
from django.db import models
from .models import *
from _datetime import datetime

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/../user/templates/user/inbox.html'
    context_object_name = 'threads'
    # was commented out

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    # success_url = '/messages/'
    # success_url = './'
    success_url = '#'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context


    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        new_message = ChatMessage.objects.create(user=user, thread=thread, message=message)
        updated_time = datetime.now()
        thread.updated = new_message.timestamp
        thread.save()
        return super().form_valid(form)

chat/templates/chat/thread.html
{% extends "user/base.html" %}

<style>
    body
    {
        font-family: 'Helvetica','Arial', sans-serif;
        background-color: #42A1C9
    }
    #chat-items ul
    {
        background-color: white;
        max-height: 120px;/*The important part*/
        overflow: scroll;
        -webkit-overflow-scrolling: touch;
    }

    #chat-items li
    {
        list-style-type: none;
    }
</style>
{% block pageheader %}
    {% if user != object.first %}
        Chat with {{ object.first }}
        {% if object.first.profile.is_verified %}
            <h4><strong><span style="color: #1C437F"><i class="fas fa-star"></i> Trusted User</span></strong></h4>
        {% endif %}
    {% else %}
        Chat with {{ object.second }}
        {% if object.second.profile.is_verified %}
            <h4><strong><span style="color: #1C437F"><i class="fas fa-star"></i> Trusted User</span></strong></h4>
        {% endif %}
    {% endif %}
{% endblock pageheader%}

{% block content %}
<ul style="text-align: left;" id='chat-items'>
{% for chat in object.chatmessage_set.all %}

    {% if chat.user.profile.is_moderator %}
    <li>
        <img src="{{ chat.user.profile.image.url }}" class="rounded-circle z-depth-0" alt="avatar image" width="50px" height="50px">
        <b>{{ chat.user }}:</b> <span style="color: #f44336;"> {{ chat.message }} </span>
    </li><br>
    {% else %}
    <li>
        <img src="{{ chat.user.profile.image.url }}" class="rounded-circle z-depth-0" alt="avatar image" width="50px" height="50px">
        <b>{{ chat.user }}:</b> {{ chat.message }}
    </li><br>
    {% endif %}



{% endfor %}
</ul>

<form style="text-align: left;" id='form' method='POST'>
    {% csrf_token %}
    {{form.as_p }}
    <input type="hidden" value="{{ user.profile.image.url }}" name="profile_image" id="profile_image">
    <input type="hidden" value="{{ object.first.profile.image.url }}" name="first_profile_image" id="first_profile_image">
    <input type="hidden" value="{{ object.second.profile.image.url }}" name="second_profile_image" id="second_profile_image">
    <input type="hidden" value="{{ object.moderator.profile.image.url }}" name="moderator_profile_image" id="moderator_profile_image">
    <input type="hidden" value="{{ object.first }}" name="first_user" id="first_user">
    <input type="hidden" value="{{ object.second }}" name="second_user" id="second_user">
    <input type='submit' style="background: #1a2a67; color: #F9F8F8;" class='btn btn-link'/>
</form>


{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
	//alert("jquery world")
	var formData = $("#form")
	var messageInput = $("#id_message")
	var chatItems = $('#chat-items')
	var loc = window.location
	var wsStart = 'ws://'

    console.log(formData);
	var profile_image = $("#profile_image");
	console.log(profile_image.val());
	profile_image = profile_image.val();
	console.log(profile_image);
	var first_profile_image = $("#first_profile_image").val();
	var second_profile_image = $("#second_profile_image").val();

  	if (loc.protocol == 'https:') {
  		wsStart = 'wss://'
  	}
  	//var webSocketEndpoint = wsStart + loc.host + '/chat/'
  	console.log(loc.host)
	var webSocketEndpoint = wsStart + loc.host + loc.pathname
	console.log(webSocketEndpoint)
	console.log(loc.pathname)
	var socket = new WebSocket(webSocketEndpoint) //ReconnectingWebSocket

	socket.onmessage = function(e){
		console.log('message', e)
		//alert(e.data)
		var msgData = JSON.parse(e.data)
        var currentUser = msgData.user
        var firstUser = $("#first_user").val();
		var secondUser = $("#second_user").val();
        if (currentUser.localeCompare(firstUser) == 0)
        {
            profile_image = first_profile_image;
        }

        else
        {
            profile_image = second_profile_image;
        }

		console.log(msgData)

	    console.log("The profile pic variable is: " + profile_image);
	    console.log("THe profile pic source is: " + profile_image.src);

	    chatItems.append(`<li><img src="${profile_image}" id="chat_image" class="rounded-circle z-depth-0" alt="avatar image" width="50px" height="50px"><b>    ${msgData.user}:</b> ${msgData.msg}</li><br>`);
		//chatItems.append(`<li><b>${msgData.user}:</b> ${msgData.msg}</li>`)
   		chatItems.animate({scrollTop: chatItems.prop("scrollHeight")}, 500);
	}

	socket.onopen = function(e){
		console.log('open', e)
		formData.submit(function(event){
			event.preventDefault()
			var messageText = messageInput.val()
			console.log(messageText)
			var jsonData = JSON.stringify({msg: messageText, user:'jmitchel3'})
			socket.send(jsonData)
			formData[0].reset()
		})
	}

	socket.onerror = function(e){
		console.log('error', e)
	}

	socket.onclose = function(e){
		console.log('closed', e)
	}


	if (socket.readyState == WebSocket.OPEN) {

	} else if (socket.readyState == WebSocket.CONNECTING){
		console.log("connecting..")
	}
})
</script>
{% endblock script%}